# Generated by Django 6.0.1 on 2026-01-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_task_options_alter_worklog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Моя Компания', max_length=200, verbose_name='Название организации')),
            ],
            options={
                'verbose_name': 'Настройки системы',
                'verbose_name_plural': 'Настройки системы',
            },
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='personnel_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Табельный номер (Логин)'),
        ),
    ]
