# Generated by Django 6.0.1 on 2026-01-23 08:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_globalsettings_alter_employeeprofile_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последняя активность'),
        ),
    ]
