# Generated by Django 6.0.1 on 2026-01-24 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_employeeprofile_last_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='last_activity',
        ),
    ]
