# Generated by Django 6.0.1 on 2026-01-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_task_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность'),
        ),
    ]
